### ISSUE TITLE
DniproServer doesn't works under Windows 10

### ISSUE THREAD

**Issue by Mark-Kovalyov** [Bazist/DniproServer#6]
During start DniproDB_v1_0_3.exe we have got an error 

> Ошибка при запуске приложения (0xc0000007b). Для выхода из приложения нажмите ОК.

Given: Windows 10

**Comment by Bazist** [comment]
Try execute server with paramater -selftest.

If it doesn't help, please describe STR (Step To Reproduce).

**Comment by Bazist** [comment]
I have reproduced on Win 10 the issue. Try install Visual C++ Redistributable for VS 2015
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Mark-Kovalyov** [comment]
Installation of "Microsoft Visual C++ 2015 Redistr. (x64) - 14.0.23026 doesn't helps.

**Comment by Bazist** [comment]
Did you use v1_0_4 version with included runtime ?
Also you can try delete all files with .dp extension, maybe it's broken by old versions.

**Comment by Mark-Kovalyov** [comment]
Fixed in:

commit 49ad0b210ec435fd597f1ca14fbb483def164f6e
Author: Bazist <bazist@pikosec.com>
Date:   Fri Apr 1 14:53:04 2016 +0300
